my_project/urls.py
from django.contrib import admin
from django.urls import include, path
from my_project.views import SignUpView, FormCompiled, NewsList
from django.contrib.auth import views as auth_views  # per evitare conflitti con le mie views

urlpatterns = [
    path('', NewsList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('report/', include('report.urls')),
    path('verify/', include('verify.urls')),
    path('user_create/', SignUpView.as_view(), name='user-create'),
    path('form_compiled', FormCompiled.as_view(), name='form-compiled'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

report/urls.py
from django.urls import path
from report.views import NewsAndInfoCreate, DonationCreate, ReadNews, SearchResults, Statistics

app_name = 'report'

urlpatterns = [
    path('report-news/', NewsAndInfoCreate.as_view(), name='report-create'),
    path('donate/', DonationCreate.as_view(), name='donation-create'),
    path('read_news/<int:pk>', ReadNews.as_view(), name='read-news'),
    path('results/', SearchResults.as_view(), name='results'),
    path('statistics/', Statistics.as_view(), name='statistics')
]

verify/urls.py
from django.urls import path

from verify.views import Dashboard, SendReportedNews, AdminDashboard, UpdateNews, InfoList

app_name = 'verify'

urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('invia_news/<int:pk>', SendReportedNews.as_view(), name='send-news'),
    path('dashboard_admin/', AdminDashboard.as_view(), name='dashboard-admin'),
    path('edit_news/<int:pk>', UpdateNews.as_view(), name='edit-news'),
    path('dashboard_info', InfoList.as_view(), name='dashboard-info')
]

verify/models.py
from django.db import models
from report.models import NewsReported


class NewsVerified (models.Model):

    resume = models.TextField()  # riassunto scritto dal verificatore. Non è necessariamente il testo finale
    final_text = models.TextField()
    image = models.ImageField(upload_to='static/img', null=True)
    title = models.CharField(max_length=70, null=True)
    newsreported_ptr = models.OneToOneField(NewsReported, on_delete=models.CASCADE)

    # notizia vera o falsa
    STATUS_CHOICES = [(True, 'Notizia vera'), (False, 'Notizia falsa')]
    status = models.BooleanField(choices=STATUS_CHOICES)

    # approvazione dell'amministratore
    WAITING = 'wait'
    ACCEPTED = 'ok'
    REJECTED = 'no'
    CHOICES = [(WAITING, 'da approvare'), (ACCEPTED, 'approvata'), (REJECTED, 'rifiutata')]
    approved = models.CharField(max_length=4, choices=CHOICES, default=WAITING)

    # categorie delle notizie
    CRONACA = 'cronaca'
    SPORT = 'sport'
    TECNOLOGIA = 'tecnologia/scienze'
    ECONOMIA = 'economia'
    CATEGORY_CHOICES = [(CRONACA, 'cronaca'), (SPORT, 'sport'), (TECNOLOGIA, 'tecnologia'), (ECONOMIA, 'economia')]
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default=CRONACA)

    class Meta:
        verbose_name_plural = 'NewsVerified'

verify/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from verify.models import NewsVerified


class SendNewsForm (forms.ModelForm):

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('news_submit', 'Invia notizia'))
    helper.inputs[0].field_classes = 'btn btn-danger'

    class Meta:
        model = NewsVerified
        fields = ('resume', 'category', 'status')


class UpdateNewsForm(forms.ModelForm):

    helper = FormHelper()
    helper.add_input(Submit('news_submit', 'Pubblica notizia'))
    helper.inputs[0].field_classes = 'btn btn-danger'

    class Meta:
        model = NewsVerified
        fields = ('title', 'final_text', 'image', 'approved')

verify/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from report.models import NewsReported, RequestedInfo
from verify.forms import SendNewsForm, UpdateNewsForm
from verify.models import NewsVerified


class SendNews (LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = NewsVerified
    form_class = SendNewsForm
    template_name = 'verify/verify_news.html'
    success_url = reverse_lazy('verify:dashboard')
    success_message = "notizia inviata correttamente all'amministratore"

    def form_valid(self, form):  # uso la pk della segnalazione per collegarla all'istanza della notizia
        pk = self.request.META.get("HTTP_REFERER")  # url della pagina attuale
        pk = pk.split('/')[-1]
        key = NewsReported.objects.get(pk=pk)
        form.instance.newsreported_ptr = key
        return super().form_valid(form)


class Dashboard (LoginRequiredMixin, ListView):

    model = NewsReported
    template_name = 'verify/dashboard.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return redirect('../dashboard_admin')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs['object_list'] = NewsReported.objects.order_by('-id')
        kwargs['pk_verified'] = NewsVerified.objects.values_list('newsreported_ptr', flat=True)
        return super(Dashboard, self).get_context_data(**kwargs)


class SendReportedNews (LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        view = ReportedNewsDetail.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = SendNews.as_view()
        return view(request, *args, **kwargs)


class ReportedNewsDetail (LoginRequiredMixin, DetailView):

    model = NewsReported
    template_name = 'verify/verify_news.html'
    success_url = reverse_lazy('verify:dashboard')

    def get_context_data(self, **kwargs):  # così il form sarà disponibile nei template
        context = super().get_context_data(**kwargs)
        context['form'] = SendNewsForm()
        return context


class AdminDashboard(LoginRequiredMixin, ListView):

    model = NewsVerified
    template_name = 'verify/dashboard_admin.html'

    def get_context_data(self, **kwargs):  # per l'ordinamento in base all'approvazione
        kwargs['object_list'] = NewsVerified.objects.order_by('-approved')
        return super(AdminDashboard, self).get_context_data(**kwargs)


class InfoList (LoginRequiredMixin, ListView):

    model = RequestedInfo
    template_name = 'verify/dashboard_info.html'


class UpdateNews(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = NewsVerified
    template_name = 'verify/edit_news.html'
    form_class = UpdateNewsForm
    success_url = reverse_lazy('verify:dashboard-admin')
    success_message = "notizia approvata correttamente"

verify/templates/verify/dashboard.html
{% extends 'base_dashboard.html' %}

{% block dash_title %}Lista segnalazioni {% endblock %}

{% block intro %} Queste notizie aspettano soltanto di essere verificate. Dai il tuo contributo cercando
una fonte che attesti la loro veridicità. Cliccando sul link o sull'oggetto accederai alla pagina di verifica
{% endblock %}


{% block th %}
    <th scope="col">OGGETTO</th>
    <th scope="col">LINK</th>
    <th scope="col">INVIATA</th>
{% endblock %}
{% block body %}
    {% for notizia in object_list %}
        <tr>
            <td><a href="{% url 'verify:send-news' notizia.pk %}" class="dashboardlink" >{{ notizia.object }}</a></td>
            <td><a href="{% url 'verify:send-news' notizia.pk %}" class="dashboardlink">{{ notizia.link }}</a></td>
            <td>{% if notizia.pk in pk_verified %}
                SI
            {% else %}
                NO
            {% endif %} </td>
        </tr>
    {% endfor %}
{% endblock %}

verify/templates/verify/dashboard_admin.html
{% extends 'base_dashboard.html' %}

{% block dash_title %}Lista notizie da pubblicare {% endblock %}
{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="text-center alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
  {% endblock %}

{% block intro %}
    Ecco la lista delle notizie verificate dai verificatori. <br>Tocca a te aggiungere gli ultimi elementi
    necessari alla pubblicazione della notizia. <br> Clicca su una delle voci per accedere al form di modifica!
{% endblock %}


    {% block th %}
        <th scope="col">CATEGORIA</th>
        <th scope="col">RIASSUNTO DEL VERIFICATORE</th>
        <th scope="col">VERA/FALSA</th>
        <th scope="col">STATUS APPROVAZIONE</th>
    {% endblock %}

    {% block body %}
        {% for notizia in object_list %}
            <tr>
                <td><a href="{% url 'verify:edit-news' notizia.pk %}" class="dashboardlink">{{ notizia.category }}</a></td>
                <td><a href="{% url 'verify:edit-news' notizia.pk %}" class="dashboardlink">{{ notizia.resume }}</a></td>
                <td><a href="{% url 'verify:edit-news' notizia.pk %}" class="dashboardlink">{{ notizia.status }}</a></td>
                <td><a href="{% url 'verify:edit-news' notizia.pk %}" class="dashboardlink">{{ notizia.approved }}</a></td>
            </tr>
        {% endfor %}
    {% endblock %}

verify/templates/verify/dashboard_info.html
{% extends 'base_dashboard.html' %}

{% block dash_title %} Richieste di informazioni ricevute {% endblock %}

{% block intro %}
    Ecco le domande ricevute dai nostri lettori. Puoi rispondere cliccando sull'indirizzo mail
{% endblock %}


{% block th %}
    <th scope="col">MAIL</th>
    <th scope="col">TESTO RICHIESTA</th>
{% endblock %}
{% block body %}
    {% for richiesta in object_list %}
        <tr>
            <td><a href="mailto:{{ richiesta.mail }}" class="dashboardlink">{{ richiesta.mail }}</a></td>
            <td>{{ richiesta.text }}</td>
        </tr>
    {% endfor %}
{% endblock %}

verify/templates/verify/edit_news.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Fatti disfatti - Modifica notizia {% endblock %}

{% block page_title %} Pubblica notizia {% endblock %}

<br><br>

{% block content %}

    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Dati ricevuti dal verificatore</th>
        </tr>
        <tr>
            <th>Riassunto</th>
            <th>Categoria</th>
            <th>Veridicità</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.resume }}</td>
            <td>{{ object.category }}</td>
            <td>{{ object.status }}</td>
        </tr>
        </tbody>
    </table>
    <br><br>
    <table  class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Inserisci gli ultimi dati mancanti</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                {% crispy form %}
            </td>
        </tr>
        </tbody>

    </table>


{% endblock %}

verify/templates/verify/verify_news.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Fatti disfatti - Invia notizia {% endblock %}
{% block page_title %}  {% endblock %}
{% block intro %} {% endblock %}
<br><br>

{% block content %}

    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Dati inviati dall'utente</th>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.object }}</td>
            <td>{{ object.link }}</td>
        </tr>
        </tbody>
    </table>
    <br><br>
    <table  class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Inserimento dei dati da inviare all'amministratore</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                {% crispy form %}
            </td>
        </tr>
        </tbody>

    </table>


{% endblock %}