my_project/urls.py
from django.contrib import admin
from django.urls import include, path
from my_project.views import SignUpView, FormCompiled, NewsList
from django.contrib.auth import views as auth_views  # per evitare conflitti con le mie views

urlpatterns = [
    path('', NewsList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('report/', include('report.urls')),
    path('verify/', include('verify.urls')),
    path('user_create/', SignUpView.as_view(), name='user-create'),
    path('form_compiled', FormCompiled.as_view(), name='form-compiled'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

report/urls.py
from django.urls import path
from report.views import NewsAndInfoCreate, DonationCreate, ReadNews, SearchResults, Statistics

app_name = 'report'

urlpatterns = [
    path('report-news/', NewsAndInfoCreate.as_view(), name='report-create'),
    path('donate/', DonationCreate.as_view(), name='donation-create'),
    path('read_news/<int:pk>', ReadNews.as_view(), name='read-news'),
    path('results/', SearchResults.as_view(), name='results'),
    path('statistics/', Statistics.as_view(), name='statistics')
]

verify/urls.py
from django.urls import path

from verify.views import Dashboard, SendReportedNews, AdminDashboard, UpdateNews, InfoList

app_name = 'verify'

urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('invia_news/<int:pk>', SendReportedNews.as_view(), name='send-news'),
    path('dashboard_admin/', AdminDashboard.as_view(), name='dashboard-admin'),
    path('edit_news/<int:pk>', UpdateNews.as_view(), name='edit-news'),
    path('dashboard_info', InfoList.as_view(), name='dashboard-info')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container-fluid">
      <a class="navbar-brand">Fatti disfatti</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'verify:dashboard' %}">Dashboard</a>
                </li>
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'verify:dashboard-info' %}">Richieste di info</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'report:report-create' %}">Segnala notizia</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'report:statistics' %}">Statistiche</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'report:donation-create' %}">Dona</a>
                </li>
        </ul>
        <form class="d-flex" action="{% url 'report:results' %}" method="get">
          <div class="dropdown" >
            <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-expanded="false">
              Seleziona categoria
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <input class="dropdown-item" type="submit" value="cronaca" name="category">
              <input class="dropdown-item" type="submit" value="sport" name="category">
              <input class="dropdown-item" type="submit" value="economia" name="category">
              <input class="dropdown-item" type="submit" value="tecnologia" name="category">
            </div>
          </div>
          <input class="form-control me-2" type="search" placeholder="Cerca notizia" aria-label="Search" name="q">
          <button class="btn btn-outline-light" type="submit">Cerca</button>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>
  <br><br><br>
  {% block messages %}  {% endblock %}


  <h1> {% block page_title %}{% endblock %}</h1><br>
  <h3> {% block intro %}{% endblock %}</h3>
  {% block content %}{% endblock %}

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

  </body>
</html>

templates/base_dashboard.html
{% extends 'base.html' %}

{% block title %} Fatti disfatti - {% block dash_title %}{% endblock %} {% endblock %}
{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="text-center alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
  {% endblock %}

{% block page_title %} Benvenuto nella dashboard, {{ request.user }} {% endblock %}


{% block content %}
    <br><br>
    <table class="table table-bordered table-danger">
        <thead>
        <tr>
            {% block th %}{% endblock %}
        </tr>
        </thead>
        <tbody>
            {% block body %}{% endblock %}
        </tbody>
    </table>

{% endblock %}

templates/form_compiled.html
{% extends 'base.html' %}

{% block title %}Operazione completata {% endblock%}

{% block page_title %}Complimenti!{% endblock %}
{% block intro %}Il form è stato compilato con successo.{% endblock %}

{% block content %}
    <br><br>
    <a class="btn btn-danger" href="{% url 'home' %}" role="button">Vai alla homepage</a>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %} Fatti disfatti - Home {% endblock %}
{% block page_title %} Benvenuto/a! {% endblock %}
{% block intro %}
    Qui di seguito troverai una lista di notizie segnalate da voi e  verificate dai nostri verificatori!
{% endblock %}
{% block content %}
    <br><br><br><br>
    <table class="newstable">
        <thead></thead>
        <tbody>
            {% for notizia in object_list %}
                <tr class="newstitle">
                    <td><a href="{% url 'report:read-news' notizia.pk %}">{{ notizia.title }}</a> </td>
                    {% if notizia.status %}
                        <td class="newstrue">vera
                        {% else %}
                        <td class="newsfalse">falsa
                        {% endif %}
                    </td>
                </tr>
                <tr class="imgrow">
                    <td><img src="{{notizia.image}}" alt="{{ notizia.image }}"></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}